name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: CareFlowX.Api } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet publish -c Release -o out

  build-frontend:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ../careflowx-aurelia } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || npm install
      - run: npm run build
